### ISSUE TITLE
server hang for 10 secs

### ISSUE THREAD

**Issue by johnneijzen** [danjono/Inventory-Rollback#23]
I am not sure if it is from this plugin but i installed beta 2.0 version at last plugin that this problem started happing and it only at start of server boot up and when player join in

i had feeling maybe it has to with players joining server and there inventory getting saved i am using authme before login in so it be 
could that is causing issue

also i guesssing because of that com.google.code.gson dependency

[latest.log](https://github.com/danjono/Inventory-Rollback/files/4682553/latest.log)

**Comment by johnneijzen** [comment]
Okay i had to completely remove beta version it KEEP ON CRASH server everytime i type /ir

**Comment by Aurelien30000** [comment]
Seems completely unrelated, _Server thread dump_ doesn't mention IR at all.

**Comment by johnneijzen** [comment]
i just close this now since i am not using plugin anymore
