### ISSUE TITLE
MySQL support doesn't work at all - Version 2.0

### ISSUE THREAD

**Issue by iTiamo** [danjono/Inventory-Rollback#26]
I can't get MySQL support to work at all. Backups can be made but are never shown in the backup restore menu.

**Comment by danjono** [comment]
I can't reproduce this as I can save my backups to MySQL and access them via `/ir` or `/ir restore danjono`

Have you tried it again with a default config and just your MySQL details added and enabled? I can only assume something is invalid in the config which is breaking something.

**Comment by iTiamo** [comment]
MySQL support started working after deleting config.yml and configuring with a fresh database.

**Comment by iTiamo** [comment]
Resolved the issue with a fresh config.yml and database, but realised the performance is quite poor. Backups would show up but it would take a few seconds for the first backup to appear in the GUI, after which the following backups take about a second each.

I suppose the performance is a plugin issue, because I have a dynmap running in the same environment and the tiles load pretty fast.
