### ISSUE TITLE
errors in console from inventory rollback plugin. unable to restore inventories

### ISSUE THREAD

**Issue by SirLemonade** [danjono/Inventory-Rollback#3]
Unable to restore inventories. simply say no backups are found.
errors in console:
https://pastebin.com/DpnXrbsz

**Comment by danjono** [comment]
Pastebin link is now invalid however I would have a guess that the player save file you are trying to access is corrupted. Try removing the save file and allowing a fresh one to be generated.

**Comment by SirLemonade** [comment]
Hello! i see you closed my issue due to a expired pastebin link.
Luckily i still use the plugin and see the issue come by every day. Since it doesn't happen every time i can still use it. It helps a lot. 
Here is a new pastebin link that won't expire. Until 6 months from now. 

https://pastebin.com/cewXq2By

Says unable to save item stacks. Which doesn't sound like a corrupt save file to me. 
I'd appreciate it if you take a look at that.
