### ISSUE TITLE
Update to 1.16.3 ? When it will be?

### ISSUE THREAD

**Issue by RavenskyPaul** [danjono/Inventory-Rollback#36]
Hello, I want to ask when it will be an update.
I have some errors in console:
[23:15:22 INFO]: [InventoryRollback] Enabling InventoryRollback v1.3.8
[23:15:22 WARN]: ** WARNING... Plugin may not be compatible with this version of Minecraft. **
[23:15:22 WARN]: ** Tested versions: 1.8.8 to 1.16.1 **
[23:15:22 WARN]: ** Please fully test the plugin before using on your server as features may be broken. **

**Comment by iCaitlyn** [comment]
Might as well change the title to be "1.16.3" now

**Comment by breadbyte** [comment]
There's a PR that exists for 1.16.2/3 support https://github.com/danjono/Inventory-Rollback/pull/33 
It has a test build if you want to try it out before danjono merges it.

**Comment by iCaitlyn** [comment]
> 
> 
> There's a PR that exists for 1.16.2/3 support #33
> It has a test build if you want to try it out before danjono merges it.

Not too sure if downgrading to 1.4.0 is advisable though, since I'm using the 2.0 beta

**Comment by RavenskyPaul** [comment]
> > There's a PR that exists for 1.16.2/3 support #33
> > It has a test build if you want to try it out before danjono merges it.
> 
> Not too sure if downgrading to 1.4.0 is advisable though, since I'm using the 2.0 beta

Can You attach here the 2.0 beta version?

**Comment by iCaitlyn** [comment]
> 
> 
> > > There's a PR that exists for 1.16.2/3 support #33
> > > It has a test build if you want to try it out before danjono merges it.
> > 
> > 
> > Not too sure if downgrading to 1.4.0 is advisable though, since I'm using the 2.0 beta
> 
> Can You attach here the 2.0 beta version?

https://github.com/danjono/Inventory-Rollback/tree/v2.0-beta

**Comment by RavenskyPaul** [comment]
> > > > There's a PR that exists for 1.16.2/3 support #33
> > > > It has a test build if you want to try it out before danjono merges it.
> > > 
> > > 
> > > Not too sure if downgrading to 1.4.0 is advisable though, since I'm using the 2.0 beta
> > 
> > 
> > Can You attach here the 2.0 beta version?
> 
> https://github.com/danjono/Inventory-Rollback/tree/v2.0-beta

Can you attach the .jar file of 2.0 beta please?

**Comment by iCaitlyn** [comment]
> 
> 
> > > > > There's a PR that exists for 1.16.2/3 support #33
> > > > > It has a test build if you want to try it out before danjono merges it.
> > > > 
> > > > 
> > > > Not too sure if downgrading to 1.4.0 is advisable though, since I'm using the 2.0 beta
> > > 
> > > 
> > > Can You attach here the 2.0 beta version?
> > 
> > 
> > https://github.com/danjono/Inventory-Rollback/tree/v2.0-beta
> 
> Can you attach the .jar file of 2.0 beta please?

https://github.com/danjono/Inventory-Rollback/releases/download/v2.0-beta/InventoryRollback-2.0-beta.jar

**Comment by danjono** [comment]
Pull request has been merged to remove notification that plugin may not be compatible with 1.16.2/1.16.3. The plugin was still compatible and required no major changes to resolve other than to remove the warning.
