### ISSUE TITLE
1.15 Support Request

### ISSUE THREAD

**Issue by ColaIan** [danjono/Inventory-Rollback#8]
Hello! I'd like to request for inventory rollback plugin to support Minecraft version 1.15.

P.S. I'm not able to start a conversation with you on spigot, and it says user not found, not sure if it's a problem you are having on the spigot forum.

Thanks!

**Comment by Aurelien30000** [comment]
You can use my temporary built version from my Pr https://github.com/danjono/Inventory-Rollback/pull/7 ^^

**Comment by danjono** [comment]
Added in v1.3.7. Download from Spigot
